Generate "tell" variants for functions not returning anything in the stub generator (WIP)
golemcloud/wasm-rpc pull request #37
Opened 2024-04-19 17:22 UTC by afsalthaj

Fixing https://github.com/golemcloud/golem/issues/278

Drafting the PR to get earlier review

I couldn’t change the wit generation and proceed, because the source generation depends on the original stub definitions.
Therefore, just changed at the site of collection function stub.

2024-04-19 17:34 UTC, afsalthaj commented
<img width="1769" alt="image" src="https://github.com/golemcloud/wasm-rpc/assets/7448613/cc0a835a-8847-4843-a164-b4e5e7457cc3">


<img width="902" alt="image" src="https://github.com/golemcloud/wasm-rpc/assets/7448613/b17309ff-bf70-43ea-a00e-68273e0629cd">


<img width="2048" alt="image" src="https://github.com/golemcloud/wasm-rpc/assets/7448613/10183d0e-d6f1-43cb-b958-dec7706b1e8e">

2024-04-19 17:43 UTC, justcoon commented on wasm-rpc-stubgen/src/stub.rs
> +            })
if results is empty, then there will be 2 functions ?

1. blocking-function_name
2. function_name 
?

2024-04-19 17:53 UTC, justcoon approved these changes

2024-04-20 07:33 UTC, vigoo requested changes
There are a couple of problems. 

Most importantly, you are sending a wrong function name to the `invoke-and-await` function - there is no `blocking-add-event` function exported on the remote worker, just `add-event`.

It also does not look nice that you generate both functions into the same function collection and then make decisions later based on their name (`starts_with`).

I suggest to:
- do not modify `stub.rs` - keep the list of functions as it is
- in `rust.rs` modify `generate_function_stub_source` so it gets a parameter that controls its behavior - based on that it can decide whether to override the function name (but not in the invoke's string parameter!) or not, and whether to use the `invoke` or the `invoke-and-await`. Then you need to call this twice in the `generate_stub_source` if the function has no return values, to generate both variants.
- Do the same in `wit.rs` - just based on the `FunctionStub` you can see if you need to generate two functions or one.
- The whole thing has to work for global functions, resource methods, and static functions.

2024-04-22 01:43 UTC, afsalthaj commented
@vigoo  Done

2024-04-22 01:44 UTC, afsalthaj commented
<img width="1792" alt="image" src="https://github.com/golemcloud/wasm-rpc/assets/7448613/c48fc949-e5ca-4898-bbdd-6175f11d1e14">

2024-04-22 07:40 UTC, vigoo approved these changes

2024-04-22 07:40 UTC, merged